# Dependencies
markdown: kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            Xiaozhou
tagline:          ''
description:      'I write about my experiences here so that I can move forward.'
url:              https://yangxiaozhou.github.io
baseurl:          ''

author:
  name:           'YANG Xiaozhou'

paginate:         5

# Custom vars
# version:          2.1.0

github:           
  repo:           https://github.com/yangxiaozhou/yangxiaozhou.github.io

plugins: 
  - jekyll-paginate
  - jekyll-archives

disqus:
  shortname: yangxiaozhou
