# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            Xiaozhou
tagline:          ''
description:      'I write about my research and in general, life, here.'
url:              https://yangxiaozhou.github.io
baseurl:          ''

author:
  name:           'YANG Xiaozhou'

paginate:         5

# Custom vars
# version:          2.1.0

github:           
  repo:           https://github.com/yangxiaozhou

plugins: 
  - jekyll-paginate
  - jekyll-archives

disqus:
  shortname: yangxiaozhou

github_username:  YangXiaozhou
linkedin_username: yangxiaozhou
youtube_username: a315345751

google_analytics: UA-89141653-4

