# Dependencies
markdown: kramdown
kramdown: 
  input: GFM
highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            杨晓州
tagline:          ''
description:      'I write about my experiences here.'
url:              https://yangxiaozhou.github.io
baseurl:          ''

author:
  name:           'Yang Xiaozhou'

paginate:         5

# Custom vars
# version:          2.1.0

github:           
  repo:           https://github.com/yangxiaozhou/yangxiaozhou.github.io

plugins: 
  - jekyll-paginate
  - jekyll-archives

disqus:
  shortname: yangxiaozhou
