# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Yang Xiaozhou
tagline:          'A personal website'
description:      'I write about my research and in general, life, here.'
url:              https://yangxiaozhou.github.io
baseurl:          http://yangxiaozhou.github.io/yangxiaozhou.github.io

author:
  name:           'Yang Xiaozhou'
  # url:            https://twitter.com/mdo

paginate:         5

# Custom vars
# version:          2.1.0

github:           YangXiaozhou
  # repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate]

disqus:
  shortname: yangxiaozhou

github_username:  YangXiaozhou
linkedin_username: yangxiaozhou
youtube_username: a315345751

google_analytics: UA-89141653-4

