# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Yang Xiaozhou
tagline:          'A personal website'
description:      'I write about my research and in general, life, here.'
url:              https://yangxiaozhou.github.io
baseurl:          /

author:
  name:           'Yang Xiaozhou'
  # url:            https://twitter.com/mdo

paginate:         5

# Custom vars
# version:          2.1.0

github:           YangXiaozhou
  # repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate]
